### PR TITLE
getKoboData: Catch errors and continue loop of submissions

### LINKED ISSUE #237: Catch Kobo API 404 errors instead of letting job fail [BNS]
## Background, context, and business value

We are fetching a list of Kobo forms from GoogleSheets then running the [getKoboData](https://github.com/OpenFn/ConSoSci/blob/master/bns/getKoboData.js) job to fetch submissions from those forms. However, sometimes those forms are not shared with the Kobo credential owner, which results in a 404.

Currently the job fails and halts if a 404 error occurs. If this happens, we would like (1) catch this 404 error, but then (2) continue to the next form in the list and keep pulling data. We should only throw any errors caught at the end of the job and show a list of forms with 404 errors.

## A clear and concise description of what you want to happen.
In the [getKoboData](https://github.com/OpenFn/ConSoSci/blob/master/bns/getKoboData.js) job, for each form we try to fetch from Kobo... if the Kobo api returns with an http error status code (not a `200`), then: 
1. catch the error & store the URL/formId of the form that caused the error
2. keep the job running and move on to the next form to process
3. at the end, (1) throw an error to force the job to fail, and then (2) print the formId that caused the error and the error message from the Kobo API

## state.json

LP `WCS Kobo Global Aggregation Account`

https://gist.github.com/aleksa-krolls/d3ff8cc35090f8c625490d002d4b5f74

## adaptor
language-http@v3.1.11 --> fine to upgrade to the latest adaptor version, if you recommend this

## expression.js
[getKoboData](https://github.com/OpenFn/ConSoSci/blob/master/bns/getKoboData.js)

### PR DESCRIPTION
**Pull request by hunterachieng**
## Description
There are instances where we are unable to fetch submissions from `kobotoolbox` and this throws a `404` error. When this happens the remaining forms in the list are skipped. 

The solution was to `catch` the error when fetching submissions for each form but still allow the other forms to be called and their submissions fetched
**Issue**
- #237

### CODE REVIEW

File: bns/getKoboData.js [hunk 1]
```diff
@@ -1,16 +1,19 @@
...
+// Here we fetch submissions for all "Deployed" forms in GoogleSheet
 // NOTE: See linked job "[BNS-1A] 1.Get FormsList (Ongoing)" for cursor & GoogleSheet query logic
 //**********************************************************//
+
 fn(state => {
-  console.log('surveys ::', JSON.stringify(state.data.surveys, null, 2)); 
-  return state; 
-})
+  state.surveySubmissions = state.surveySubmissions || [];
+  state.errors = state.errors || [];
```
Comment (mtuchi) [inline bns/getKoboData.js:7]: If we have other errors from previous run they will be carried into this step and displayed as new errors which is not accurate 

`state.errors = []` makes sure we are only collecting errors for this step. Is it not working ?
@hunterachieng

File: bns/getKoboData.js [hunk 2]
```diff
@@ -20,15 +23,33 @@ each(dataPath('surveys[*]'), state => {
         body: submission,
       };
     });
-    const count = state.data.submissions.length;
+
+    state.surveySubmissions = state.surveySubmissions || [];
```
[the remark this answers is not in the document]
Comment (mtuchi) [reply bns/getKoboData.js:27]: Maybe make sure you clearing state or reseting the values for `surveySubmissions` or `errors` back to `[]`

File: bns/getKoboData.js [hunk 3]
```diff
@@ -20,15 +23,33 @@ each(dataPath('surveys[*]'), state => {
...
+    console.log(`Error fetching submissions from  ${formId}::`, err.message);
+    return state;
+  });
+});
+
+each(
+  '$.surveySubmissions[*]',
+  post(state => state.configuration.openfnInboxUrl, {
+    body: state => {
+      const { i } = state.data;
```
[the remark this answers is not in the document]
Comment (mtuchi) [reply bns/getKoboData.js:48]: Maybe we should change the log to say 
`console.log(`Posting ${i + 1} of ${count}... for ${formId}`);`

To indicate that it's the submission of a specific form

**Review by mtuchi — CHANGES_REQUESTED** [review]
@hunterachieng left couple of suggestion. Ping me on slack if you have more question

File: bns/getKoboData.js [hunk 4]
```diff
@@ -20,15 +25,35 @@ each(dataPath('surveys[*]'), state => {
...
-    })(state);
-  })(state);
-});
\ No newline at end of file
+  })(state)
+    .then(() => {
+      return state;
+    })
+    .catch(err => {
+      state.errors = state.errors || [];
```
Comment (mtuchi) [inline bns/getKoboData.js:39]: @hunterachieng i think you forgotten this line, 
It should be removed now

File: bns/getKoboData.js [hunk 5]
```diff
@@ -20,15 +25,35 @@ each(dataPath('surveys[*]'), state => {
...
-      console.log(`Posting ${state.data.i + 1} of ${count}...`);
-      return post(state.configuration.openfnInboxUrl, {
-        body: state => state.data,
-      })(state);
-    })(state);
-  })(state);
-});
\ No newline at end of file
+  })(state)
+    .then(() => {
```
Comment (mtuchi) [inline bns/getKoboData.js:35]: @hunterachieng why not `.then((state) => {return state})` ?

Comment (mtuchi) [reply bns/getKoboData.js:35]: Actually since we are using the `.then()` approach i think we can remove the callback completely and have something like this 

```
return get(`${url}${query}`)(state).then((state) => {
  const results = state.data.results.map((submission, i) => {
    return {
      i,
      // Here we append the tags defined above to the Kobo form submission data
      form: tag,
      formName: name,
      formOwner: owner,
      body: submission,
    };
  });

  state.surveySubmissions.push(...results);
  const count = results.length;
  console.log(`Fetched ${count} submissions from ${formId} (${tag}).`);

  return state;
});
```

File: bns/getKoboData.js [hunk 6]
```diff
@@ -20,15 +25,35 @@ each(dataPath('surveys[*]'), state => {
...
+      return state;
+    });
+});
+
+each(
+  '$.surveySubmissions[*]',
+  post(state => state.configuration.openfnInboxUrl, {
+    body: state => {
+      const count = state.surveySubmissions.length;
+      console.log(`Posting ${state.count} of ${count}...`);
```
[the remark this answers is not in the document]
Comment (mtuchi) [reply bns/getKoboData.js:54]: Okay i think if we remove the mapping of `i` in line 18 we can then re-map the entire `surveySubmissions` to add the index for each submission 

```js
fn((state) => {
  const { surveySubmissions } = state;
  state.surveySubmissions = surveySubmissions.map((submission, i) => ({
    i: i++,
    ...submission,
  }));
  return state;
}); 
```

This way you can completely remove `state.count` and update the log to say 
```js
const count = state.surveySubmissions.length;
console.log(`Posting ${state.data.i} of ${count}...`);
```

[the remark this answers is not in the document]
Comment (hunterachieng) [reply bns/getKoboData.js]: @mtuchi  I had to change this implementation since the last `each` was only working on the first item and not looping through to the others

File: .DS_Store
Comment (mtuchi) [inline .DS_Store:1]: @hunterachieng delete this file, i think you tracked it accidentally

File: bns/getKoboData.js [hunk 7]
```diff
@@ -1,34 +1,54 @@
...
+});
+
+each('$.surveySubmissions[*]', state => {
+  return post(state => state.configuration.openfnInboxUrl, {
+    body: state => {
+      const count = state.surveySubmissions.length;
+      console.log(`Posting ${state.data.i} of ${count}...`);
+      return state.data;
+    },
   })(state);
```
Comment (mtuchi) [inline bns/getKoboData.js:53]: This is anti-pattern , the post function should be the second argument of `each` function

```js
each(
  "$.surveySubmissions[*]",
  post((state) => state.configuration.openfnInboxUrl, {
    body: (state) => {
      const count = state.surveySubmissions.length;
      console.log(`Posting ${state.data.i} of ${count}...`);
      return state.data;
    },
  })
);
```

Is that code not working ?

Comment (mtuchi) [reply bns/getKoboData.js:53]: Also this log 👇🏽 is not accurate 
```
 const count = state.surveySubmissions.length;
 console.log(`Posting ${state.data.i} of ${count}...`);
```

Because `count` is the total submission for each form while `i` is a submission index number for a specific `formName`.

I think if we don't want to change too much we should update the log to something like 

```
const subCount = state.data.i++
const formName = state.data.formName
console.log(`Posting ${subCount} of ${state.data.formName...`)
```

Comment (hunterachieng) [reply bns/getKoboData.js:53]: @mtuchi  The log works as intended. See this attached logs 
```
GET request succeeded with 200 ✓
Fetched 0 submissions from aGT9DSs6zf6q54okHR6UxY (bns_survey).
Posting 0 of 867...
POST request succeeded with 200 ✓
Posting 1 of 867...
POST request succeeded with 200 ✓
Posting 2 of 867...
POST request succeeded with 200 ✓
Posting 3 of 867...
POST request succeeded with 200 ✓
```

Comment (hunterachieng) [reply bns/getKoboData.js:53]: If I switch back to the `each` function you have given, this is the result 
```
Posting 0 of 867...
POST request succeeded with 200 ✓
POST request succeeded with 200 ✓
POST request succeeded with 200 ✓
POST request succeeded with 200 ✓
POST request succeeded with 200 ✓
POST request succeeded with 200 ✓
POST request succeeded with 200 ✓

```

Comment (mtuchi) [reply bns/getKoboData.js:53]: @hunterachieng i haven't run that code locally but i am pretty sure 
the log is not accurate. With the current implementation it will look something like this if we have two form that have submissions

```
GET request succeeded with 200 ✓
Fetched 1 submissions from aGT9DSs6zf6q54okHR6UxY (bns_survey).
GET request succeeded with 200 ✓
Fetched 3 submissions from q54okHR6Ux9DSaGTs6zf6Y (another_form).
// Then when we are posting to inbox it will say 
Posting 0 of 4...
POST request succeeded with 200 ✓
Posting 0 of 4...
POST request succeeded with 200 ✓
Posting 1 of 4...
POST request succeeded with 200 ✓
Posting 2 of 4...
POST request succeeded with 200 ✓
Posting 3 of 4...
```

Notice that it will say `Posting 0 of 4...` twice because the first time is for `bns_survey` form and the second time is for `another_form`.

Try running the workflow with at-least two form submissions and look at the logs

Comment (mtuchi) [reply bns/getKoboData.js:53]: Can you try this version instead 
```
each(
  '$.surveySubmissions[*]',
  post(
    state => state.configuration.openfnInboxUrl,
    state => {
      const count = state.surveySubmissions.length;
      console.log(`Posting ${state.data.i} of ${count}...`);

      return { body: state.data };
    }
  )
);
```

File: bns/getKoboData.js [hunk 8]
```diff
@@ -1,34 +1,59 @@
...
+});
+
+each(
+  '$.surveySubmissions[*]',
+  post(
+    state => state.configuration.openfnInboxUrl,
+    state => {
+      const subCount = state.data.i;
+      const formName = state.data.formName;
+      console.log(`Posting ${subCount} of ${formName}...`);
```
Comment (mtuchi) [inline bns/getKoboData.js:55]: @hunterachieng Just tiny tiny cosmetic touch on this log. 
```
const {i, formName} = state.data;
const count = state.surveySubmissions.length;
console.log(`Posting ${i} of ${count} from ${formName}`);
```

**Review by mtuchi — APPROVED** [review]
All is good here @hunterachieng

**Comment by aleksa-krolls** [comment]
hey @mtuchi @hunterachieng for existing clients, please don't merge PRs until consultants have approved and tested the changes. In this case - this change went right to prod. 

Looks like it's all ok, but we need to make sure the issue requester tests as well before changes go live.

**Comment by mtuchi** [comment]
@aleksa-krolls noted
